-- Schema for smart_internship
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(150) UNIQUE NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(20) NOT NULL CHECK(role IN('STUDENT','COMPANY','INSTITUTION','ADMIN')),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS students(id SERIAL PRIMARY KEY,user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,college_name VARCHAR(150),course VARCHAR(100),branch VARCHAR(100),year INTEGER,skills TEXT,phone VARCHAR(20));
CREATE TABLE IF NOT EXISTS companies(id SERIAL PRIMARY KEY,user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,company_name VARCHAR(150) NOT NULL,industry VARCHAR(100),website VARCHAR(200),location VARCHAR(150),description TEXT);
CREATE TABLE IF NOT EXISTS institutions(id SERIAL PRIMARY KEY,user_id INTEGER UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,institution_name VARCHAR(150) NOT NULL,address TEXT,contact_number VARCHAR(20));
CREATE TABLE IF NOT EXISTS student_institution_memberships(student_user_id INTEGER PRIMARY KEY REFERENCES students(user_id) ON DELETE CASCADE,institution_id INTEGER NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,assigned_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_student_institution_memberships_institution ON student_institution_memberships(institution_id);
CREATE TABLE IF NOT EXISTS internships(id SERIAL PRIMARY KEY,company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,title VARCHAR(150) NOT NULL,description TEXT,skills_required TEXT,location VARCHAR(150),stipend NUMERIC(10,2),duration_months INTEGER,start_date DATE,end_date DATE,status VARCHAR(20) DEFAULT 'POSTED' CHECK(status IN('POSTED','CLOSED')),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS applications(id SERIAL PRIMARY KEY,internship_id INTEGER NOT NULL REFERENCES internships(id) ON DELETE CASCADE,student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,status VARCHAR(20) DEFAULT 'APPLIED' CHECK(status IN('APPLIED','SELECTED','REJECTED','ONGOING','COMPLETED')),applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(internship_id,student_id));
CREATE TABLE IF NOT EXISTS weekly_reports(id SERIAL PRIMARY KEY,application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,content TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS internship_events(id SERIAL PRIMARY KEY,application_id INTEGER NOT NULL REFERENCES applications(id) ON DELETE CASCADE,student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,internship_id INTEGER NOT NULL REFERENCES internships(id) ON DELETE CASCADE,event_type VARCHAR(50) NOT NULL,progress_percent NUMERIC(5,2) DEFAULT 0,duration_minutes INTEGER DEFAULT 0,created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS certificates(id SERIAL PRIMARY KEY,application_id INTEGER UNIQUE NOT NULL REFERENCES applications(id) ON DELETE CASCADE,certificate_number VARCHAR(100) UNIQUE NOT NULL,certificate_url TEXT,issued_date DATE DEFAULT CURRENT_DATE,verified BOOLEAN DEFAULT FALSE);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email); CREATE INDEX IF NOT EXISTS idx_users_role ON users(role); CREATE INDEX IF NOT EXISTS idx_internships_company ON internships(company_id); CREATE INDEX IF NOT EXISTS idx_applications_student ON applications(student_id); CREATE INDEX IF NOT EXISTS idx_applications_internship ON applications(internship_id); CREATE INDEX IF NOT EXISTS idx_weekly_reports_application ON weekly_reports(application_id); CREATE INDEX IF NOT EXISTS idx_internship_events_application ON internship_events(application_id); CREATE INDEX IF NOT EXISTS idx_internship_events_internship ON internship_events(internship_id); CREATE INDEX IF NOT EXISTS idx_certificates_number ON certificates(certificate_number);
